import {
  BellRing, CalendarClock, Check, CheckCheck, ChevronRight,
  Clock3, PlugZap, Tag
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import {
  getUserNotifications,
  markAllUserNotificationsRead,
  markUserNotificationRead,
  subscribeToBookings,
} from "../services/bookings";

function formatDate(dateText) {
  if (!dateText) return "Charging day";
  const value = new Date(`${dateText}T00:00:00`);
  if (Number.isNaN(value.getTime())) return dateText;
  return value.toLocaleDateString([], {
    weekday: "short",
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function formatDeliveredAt(value) {
  if (!value) return "Recently";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "Recently";
  return date.toLocaleString([], {
    day: "numeric",
    month: "short",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function NotificationCard({ item, onRead, onViewBooking }) {
  const unread = !item.notificationReadAt;
  const start = item.scheduledStart || item.windowStart;
  const end = item.scheduledEnd || item.windowEnd;

  return (
    <article className={`customer-notification-card ${unread ? "unread" : "read"}`}>
      <div className="customer-notification-status">
        <span className="notification-status-icon"><BellRing size={18} /></span>
        <div>
          <div className="notification-card-kicker">
            {unread && <span className="notification-new-label">NEW</span>}
            <span>{formatDeliveredAt(item.notifiedAt || item.updatedAt)}</span>
          </div>
          <h3>Charging schedule confirmed</h3>
        </div>
      </div>

      <p className="customer-notification-message">{item.notification}</p>

      <div className="customer-notification-meta">
        <span><CalendarClock size={14} /> {formatDate(item.date)}</span>
        {start && end && <span><Clock3 size={14} /> {start}–{end}</span>}
        {item.chargerId && <span><PlugZap size={14} /> Charger {String(item.chargerId).padStart(2, "0")}</span>}
        {Number.isFinite(Number(item.price)) && <span><Tag size={14} /> Rs. {Number(item.price).toFixed(2)}/kWh</span>}
      </div>

      <div className="customer-notification-actions">
        {unread && (
          <button type="button" className="notification-read-button" onClick={() => onRead(item.id)}>
            <Check size={15} /> Mark as read
          </button>
        )}
        <button type="button" className="notification-booking-button" onClick={() => onViewBooking(item.id)}>
          View booking <ChevronRight size={15} />
        </button>
      </div>
    </article>
  );
}

export default function Notifications() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [version, setVersion] = useState(0);

  useEffect(() => subscribeToBookings(() => setVersion((value) => value + 1)), []);

  const currentNotifications = useMemo(() => getUserNotifications(user?.id), [user?.id, version]);
  const unread = currentNotifications.filter((item) => !item.notificationReadAt);
  const previous = currentNotifications.filter((item) => Boolean(item.notificationReadAt));

  async function markOneRead(bookingId) {
    await markUserNotificationRead(bookingId, user.id);
    setVersion((value) => value + 1);
  }

  async function markAllRead() {
    await markAllUserNotificationsRead(user.id);
    setVersion((value) => value + 1);
  }

  async function viewBooking(bookingId) {
    await markUserNotificationRead(bookingId, user.id);
    navigate(`/booking?highlight=${encodeURIComponent(bookingId)}`);
  }

  return (
    <section className="page-width inner-page notifications-page">
      <div className="notifications-heading">
        <div>
          <p className="eyebrow">CUSTOMER NOTIFICATIONS</p>
          <h1>Notifications</h1>
          <p>Charging schedule updates generated by the station optimization.</p>
        </div>
        {unread.length > 0 && (
          <button type="button" className="notification-mark-all" onClick={markAllRead}>
            <CheckCheck size={17} /> Mark all as read
          </button>
        )}
      </div>

      {currentNotifications.length === 0 ? (
        <div className="panel notifications-empty-state">
          <span><BellRing size={25} /></span>
          <h2>No notifications yet</h2>
          <p>Your confirmed flexible-charging schedule will appear here after the station optimization is published.</p>
        </div>
      ) : (
        <div className="notifications-content">
          {unread.length > 0 && (
            <section className="notification-group">
              <div className="notification-group-heading">
                <h2>New</h2>
                <span>{unread.length} unread</span>
              </div>
              <div className="notification-list">
                {unread.map((item) => (
                  <NotificationCard key={item.id} item={item} onRead={markOneRead} onViewBooking={viewBooking} />
                ))}
              </div>
            </section>
          )}

          <section className="notification-group">
            <div className="notification-group-heading">
              <h2>Previous notifications</h2>
              <span>{previous.length}</span>
            </div>
            {previous.length > 0 ? (
              <div className="notification-list">
                {previous.map((item) => (
                  <NotificationCard key={item.id} item={item} onRead={markOneRead} onViewBooking={viewBooking} />
                ))}
              </div>
            ) : (
              <div className="panel notifications-previous-empty">Read notifications will remain here for reference.</div>
            )}
          </section>
        </div>
      )}
    </section>
  );
}
